name: konoyubi
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_facebook_auth: ^3.5.0
  flutter_dotenv: ^5.0.0
  flutter_hooks: ^0.17.0
  font_awesome_flutter: ^9.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  geolocator: ^7.4.0
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.5
  hooks_riverpod: ^0.14.0+4
  intl: ^0.17.0
  sentry_flutter: ^5.1.0
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.1"
  flutter_native_splash: ^1.2.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_light.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#fefefe"
  image: assets/icons/splash_light.png
  color_dark: "#1e1e1e"
  image_dark: assets/icons/splash_dark.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
